### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by akien-mga** [Jbat1Jumper/erythrina#5]
Hi there,

I couldn't find licensing information in the repo for the code nor the assets. It would be great if you could choose a fitting license (or more than one if you want a distinct license for code and assets) and document it in e.g. a LICENSE.md file.

This project is already great as learning material, but some users might be interested in either reusing parts of the code or parts of the assets, and for this they would need licensing info to know if they are allowed to do this or not.

**Comment by Jbat1Jumper** [comment]
I have this kinda abandoned, but I'll continue this when I'll have time. You're right, lets add a gnu gpl for the sake of copylefting.
